name: build and push to heroku

on:
  release:
    types: [published]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    

      - name: Login to Heroku Container registry using docker
        run: docker login --username=_ --password=${{secrets.HEROKU_PASSWORD}} registry.heroku.com

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.heroku.com/upscape-nikhil/web
          timeout-minutes: 10
          build-args: | 
            MONGODB_URI=${{secrets.MONGODB_URI}}
            DATABASE=${{secrets.DATABASE}}
            PASSWORD_SECRET=${{secrets.PASSWORD_SECRET}}
  
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login          
        
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 

